<a href="https://colab.research.google.com/github/AhmedMohamedNabih/AI-course/blob/main/Yet_another_copy_of_Yet_another_copy_of_Yet_another_copy_of_Yet_another_copy_of_Yet_another_copy_of_100_Numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
import numpy as np
print(np.version)
np.show_config()

<module 'numpy.version' from '/usr/local/lib/python3.10/dist-packages/numpy/version.py'>
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep139863411681952
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -fno-strict-aliasing
    commands: cc
    linker: ld.bfd
    linker args: -Wl,--strip-debug, -fno-strict-aliasing
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    linker args: -Wl,--strip-debug
    name: gcc
    vers

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
import numpy as np
null=np.zeros(10)
print(null)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr.nbytes)


32


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
import numpy as np
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
import numpy as np
null=np.zeros(10)
null[5]=1
print(null)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
import numpy as np
vector=np.arange(10,50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
import numpy as np
arr=[1,2,3,4,5,6,7,8,9,10]
reverse=arr[::-1]
print(reverse)

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
import numpy as np
arr=np.arange(0,9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
import numpy as np
array=np.array([1,2,0,0,4,0])
non_zero=np.nonzero(array)
print(non_zero[0])

[0 1 4]


#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
import numpy as np
arr=np.eye(3)
print(arr)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
import numpy as np
arr=np.random.rand(3,3,3)
print(arr)

[[[0.92923436 0.99748529 0.10955137]
  [0.87092777 0.54573181 0.11841009]
  [0.3949765  0.72425634 0.19150727]]

 [[0.55758742 0.44188278 0.74298849]
  [0.40231175 0.53635473 0.24271095]
  [0.83945344 0.20203656 0.32331427]]

 [[0.47708955 0.00565687 0.1915877 ]
  [0.57436787 0.34561535 0.94308404]
  [0.88521314 0.32458959 0.92473746]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
import numpy as np
arr=np.random.rand(10,10)
min=np.min(arr)
max=np.max(arr)
print(arr)
print('min number= ',min)
print('max-number= ',max)

[[0.29862489 0.54509908 0.75258052 0.83380425 0.15226591 0.37304853
  0.68090566 0.94270584 0.51483605 0.93172481]
 [0.90506334 0.29126621 0.60903076 0.37922454 0.37391335 0.93263934
  0.8284158  0.76025905 0.83153928 0.08954058]
 [0.99074038 0.8828611  0.46849752 0.4821654  0.84485322 0.11210904
  0.75849442 0.58867964 0.99433233 0.2570836 ]
 [0.84571405 0.39818319 0.78683093 0.40135153 0.38192493 0.40599405
  0.51825193 0.88381229 0.78363629 0.40322599]
 [0.44951274 0.36174686 0.21136999 0.34237562 0.093735   0.95120521
  0.55593202 0.14617798 0.93426505 0.33924707]
 [0.68324056 0.17308492 0.26425623 0.37990481 0.45600579 0.57910348
  0.98478506 0.68112884 0.9437574  0.06133914]
 [0.26307496 0.62156094 0.37719927 0.92877788 0.4975202  0.6446477
  0.92038276 0.26429724 0.63988609 0.56520136]
 [0.04751129 0.35283094 0.05825199 0.59419806 0.64165069 0.52993504
  0.64750622 0.36658458 0.17018152 0.95640001]
 [0.10989774 0.36579883 0.41687568 0.20034027 0.76468067 0.11599471
  0.05481436 

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
import numpy as np
arr=np.random.rand(30)
mean=np.mean(arr)
print(arr)
print('mean= ',mean)


[0.41560906 0.26250022 0.76405165 0.86673556 0.06070246 0.05698079
 0.34709061 0.72343626 0.02660786 0.32732813 0.10364823 0.0822258
 0.92155083 0.0074271  0.60345522 0.18671086 0.4075598  0.84796557
 0.44627015 0.9037392  0.33702053 0.28568961 0.15693624 0.30064617
 0.7963373  0.82141577 0.80294867 0.89862201 0.95112471 0.34227627]
mean=  0.4684870878907057


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
import numpy as np
array=np.ones((5,5))
array[1:-1, 1:-1] = 0
print(array)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
import numpy as np
array=np.array([[1,2,3],[4,5,6],[7,8,9]])
border=np.pad(array,pad_width=1)
print(border)

[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 0 0 0 0]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
False
False
nan
True
False



#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
import numpy as np
array=np.array([1,2,3,4])
arr=np.diag(array,k=-1)
print(arr)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
import numpy as np
board=np.tile([[1,0],[0,1]],(4,4))
print(board)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [ ]:
import numpy as np
shape = (6, 7, 8)
index = np.unravel_index(99, shape)
print(index)


(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
import numpy as np
board=np.tile([[1,0],[0,1]],(4,4))
print(board)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
import numpy as np
arr=np.random.rand(5,5)
print(arr)

[[0.71684001 0.17690101 0.06354289 0.12544112 0.33310733]
 [0.86241529 0.21208926 0.3336669  0.16169395 0.40878102]
 [0.38786152 0.94107238 0.29862957 0.95049698 0.22703631]
 [0.44862848 0.26344316 0.43058842 0.68420013 0.44249604]
 [0.6052672  0.08964276 0.23411321 0.77570744 0.29517101]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
import numpy as np
color=np.dtype([
    ('R',np.uint8),
    ('G',np.uint8),
    ('B',np.uint8),
    ('A',np.uint8)
])
colors=np.array([(255,0,0,255),(0,255,0,255),(0,0,255,255)],dtype=color)
print(color)

[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
import numpy as np
arr1=np.random.rand(5,3)
arr2=np.random.rand(3,2)
result=np.dot(arr1,arr2)
print(result)

[[0.40283129 0.72828994]
 [0.33726674 0.82124448]
 [0.3359326  0.40061225]
 [0.44971355 0.93043315]
 [0.62892266 1.23945616]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
import numpy as np
arr=np.array([1,2,4,7,8,6,5,10,3])
x=(arr>=3) &(arr<=8)
arr[x]=-arr[x]
print(arr)


[ 1  2 -4 -7 -8 -6 -5 10 -3]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
-1+1+2+3+4

9

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
nan

NameError: name 'nan' is not defined

#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
import numpy as np
def round(arr):
  return np.where(arr>=0,np.ceil(arr),np.floor(arr))
arr=np.array([1.2,-1,4,2-5,-3.1])
rounded=round(arr)
print(rounded)

[ 2. -1.  4. -3. -4.]


#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
import numpy as np
arr1=np.array([1,2,3,4,5])
arr2=np.array([5,8,9,2,1])
common=np.intersect1d(arr1,arr2)
print(common)


[1 2 5]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
import warnings
warnings.simplefilter('ignore')

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
import numpy as np
arr1=np.sqrt(-1)
arr2=np.emath.sqrt(-1)
print(arr1)
print(arr2)
print(arr1==arr2)

nan
1j
False


<ipython-input-13-e88013d2af52>:2: RuntimeWarning: invalid value encountered in sqrt
  arr1=np.sqrt(-1)


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
import numpy as np
today=np.datetime64('today')
yesterday=today-np.timedelta64(1)
tommorow=today+np.timedelta64(1)
print(today)
print(tommorow)
print(yesterday)

2024-08-21
2024-08-22
2024-08-20


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
import numpy as np
start=np.datetime64('2016-07-01')
end=np.datetime64('2016-08-01')
result=np.arange(start,end, dtype='datetime64[D]')
print(result)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
import numpy as np
A = np.array([1.0, 2.0, 3.0])
B = np.array([4.0, 5.0, 6.0])
A += B
A *= -0.5
print(A)


[-2.5 -3.5 -4.5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:
import numpy as np
randdom=np.random.rand(5)
print((randdom))

[0.77741642 0.44733144 0.49652666 0.37582644 0.72056596]


In [ ]:
import numpy as np
array=np.random.rand(5)*10
integar=np.floor(array)
print(integar)

[6. 9. 3. 7. 0.]


In [ ]:
import numpy as np
array=np.randfom.rand(5)*10
integer=np.trace(array)
print(integar)

[6. 9. 3. 7. 0.]


In [ ]:
import numpy as np
array = np.random.random(5) * 10
integer_part = array.astype(int)

print(array)
print(integer_part)


TypeError: Cannot construct a dtype from an array

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
import numpy as np
arr=np.tile(np.arange(5),(5,1))
print(arr)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [ ]:
import numpy as np
def integar(n):
  for i in range(n):
    yield i
array=np.array(list(integar(10)))
print(array)


[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [ ]:
import numpy as np
vector=np.linspace(0,1,10)
print(vector)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
import numpy as np
vector=np.random.rand(10)
sorted=np.sort(vector)
print(sorted)


[0.11987812 0.21386632 0.23473105 0.37301979 0.45212485 0.71846157
 0.79552111 0.8607206  0.87246369 0.91671673]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [ ]:
import numpy as np
array=[1,2,3,4]
result=sum(array)
print(result)

10


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [ ]:
import numpy as np
arr1=[1,2,3,4]
arr2=[3,2,4,4]
equal=np.array_equal(arr1,arr2)
print(equal)

False


#### 43. Make an array immutable (read-only) (★★☆)

In [ ]:
import numpy as np
array=np.array([1,2,3,4,5])
array.flags.writeable=False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [ ]:
import numpy as np




```
# This is formatted as code
```

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
import numpy as np
vector=np.random.rand(10)
max_value=np.argmax(vector)
vector[max_value]=0
print(vector)


[0.50757393 0.86877265 0.72279434 0.16289499 0.         0.56271023
 0.50913144 0.52419185 0.85031603 0.207176  ]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [ ]:
import numpy as np
num_points = 5
indices = np.indices((num_points, num_points)) / (num_points - 1)
structured_array = np.zeros(indices[0].size, dtype=[('x', 'f4'), ('y', 'f4')])
structured_array['x'] = indices[0].flatten()
structured_array['y'] = indices[1].flatten()
print("Structured array:\n", structured_array)


Structured array:
 [(0.  , 0.  ) (0.  , 0.25) (0.  , 0.5 ) (0.  , 0.75) (0.  , 1.  )
 (0.25, 0.  ) (0.25, 0.25) (0.25, 0.5 ) (0.25, 0.75) (0.25, 1.  )
 (0.5 , 0.  ) (0.5 , 0.25) (0.5 , 0.5 ) (0.5 , 0.75) (0.5 , 1.  )
 (0.75, 0.  ) (0.75, 0.25) (0.75, 0.5 ) (0.75, 0.75) (0.75, 1.  )
 (1.  , 0.  ) (1.  , 0.25) (1.  , 0.5 ) (1.  , 0.75) (1.  , 1.  )]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [ ]:
import numpy as np

X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])
C = 1.0 / (X[:, np.newaxis] - Y[np.newaxis, :])
print(C)


[[-0.33333333 -0.25       -0.2       ]
 [-0.5        -0.33333333 -0.25      ]
 [-1.         -0.5        -0.33333333]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [ ]:
import numpy as np
def print_numpy_limits():
    int_types = [np.int8, np.int16, np.int32, np.int64]
    print("(integers):")
    for dtype in int_types:
        print(f"{dtype.__name__}: min={np.iinfo(dtype).min}, max={np.iinfo(dtype).max}")

    # الأنواع غير الصحيحة (unsigned integers)
    uint_types = [np.uint8, np.uint16, np.uint32, np.uint64]
    print("\nالأنواع غير الصحيحة (unsigned integers):")
    for dtype in uint_types:
        print(f"{dtype.__name__}: min={np.iinfo(dtype).min}, max={np.iinfo(dtype).max}")

    # الأنواع العائمة (floating-point)
    float_types = [np.float16, np.float32, np.float64]
    print("\nالأنواع العائمة (floating-point):")
    for dtype in float_types:
        print(f"{dtype.__name__}: min={np.finfo(dtype).min}, max={np.finfo(dtype).max}")

print_numpy_limits()


(integers):
int8: min=-128, max=127
int16: min=-32768, max=32767
int32: min=-2147483648, max=2147483647
int64: min=-9223372036854775808, max=9223372036854775807

الأنواع غير الصحيحة (unsigned integers):
uint8: min=0, max=255
uint16: min=0, max=65535
uint32: min=0, max=4294967295
uint64: min=0, max=18446744073709551615

الأنواع العائمة (floating-point):
float16: min=-65504.0, max=65504.0
float32: min=-3.4028234663852886e+38, max=3.4028234663852886e+38
float64: min=-1.7976931348623157e+308, max=1.7976931348623157e+308


#### 49. How to print all the values of an array? (★★☆)

In [ ]:
import numpy as np
array=np.random.rand(4,4)
print(array)

[[0.12476871 0.70415234 0.89705797 0.84533575]
 [0.48633881 0.5011504  0.79012487 0.39631383]
 [0.4563006  0.07681519 0.66191613 0.56869332]
 [0.19752371 0.71917498 0.38803112 0.23604139]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [ ]:
import numpy as np
vector=np.array([1.2,3.2,6.5,2.9])
scaler=7
closest_value=vector[np.argmin(np.abs(scaler-vector))]
print(closest_value)

6.5


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [ ]:
import numpy as np

position = np.dtype([
    ('x', np.int32),
    ('y', np.int32),
    ('R', np.uint8),
    ('G', np.uint8),
    ('B', np.uint8)
])
data = np.array([
    (10, 20, 255, 0, 0),
    (5, 10, 0, 255, 0),
    (20, 50, 0, 0, 255)
], dtype=position)
print("Data type of array:\n", data.dtype)


Data type of array:
 [('x', '<i4'), ('y', '<i4'), ('R', 'u1'), ('G', 'u1'), ('B', 'u1')]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [ ]:
import numpy as np
from scipy.spatial.distance import pdist, squareform
points = np.random.rand(100, 2)
distances = pdist(points)
distance_matrix = squareform(distances)
print(distance_matrix)


[[0.         0.75019018 0.87238926 ... 0.64387018 0.87499051 0.91295153]
 [0.75019018 0.         0.27887068 ... 0.74306981 0.31349563 0.18851175]
 [0.87238926 0.27887068 0.         ... 0.62937501 0.04004018 0.3795703 ]
 ...
 [0.64387018 0.74306981 0.62937501 ... 0.         0.60171082 0.92473233]
 [0.87499051 0.31349563 0.04004018 ... 0.60171082 0.         0.41953093]
 [0.91295153 0.18851175 0.3795703  ... 0.92473233 0.41953093 0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [ ]:
import numpy as np
float_array=np.array([1.2,2.3,3.4,5.1,7.8],dtype=np.float32)
float_array.dtype=np.int32
print(float_array)



[1067030938 1075000115 1079613850 1084437299 1090099610]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
import numpy as np
data=np.genfromtxt('data_txt',dtype=float,filling_values=np.nan)
print(data)

FileNotFoundError: data_txt not found.

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [ ]:
import numpy as np
array=np.array([1,2,3,4,5])
for index, value in enumerate(array):
  print(index,value)

0 1
1 2
2 3
3 4
4 5


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [ ]:
import numpy as np
size = (100, 100)
x = np.linspace(-1, 1, size[0])
y = np.linspace(-1, 1, size[1])
X, Y = np.meshgrid(x, y)
sigma = 0.2
Z = np.exp(- (X**2 + Y**2) / (2 * sigma**2))
print(Z)


[[1.38879439e-11 2.28961804e-11 3.73643128e-11 ... 3.73643128e-11
  2.28961804e-11 1.38879439e-11]
 [2.28961804e-11 3.77474939e-11 6.16001946e-11 ... 6.16001946e-11
  3.77474939e-11 2.28961804e-11]
 [3.73643128e-11 6.16001946e-11 1.00525455e-10 ... 1.00525455e-10
  6.16001946e-11 3.73643128e-11]
 ...
 [3.73643128e-11 6.16001946e-11 1.00525455e-10 ... 1.00525455e-10
  6.16001946e-11 3.73643128e-11]
 [2.28961804e-11 3.77474939e-11 6.16001946e-11 ... 6.16001946e-11
  3.77474939e-11 2.28961804e-11]
 [1.38879439e-11 2.28961804e-11 3.73643128e-11 ... 3.73643128e-11
  2.28961804e-11 1.38879439e-11]]


#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [ ]:
import numpy as np

n, m, p = 5, 5, 5
array = np.zeros((n, m), dtype=int)
array[np.unravel_index(np.random.permutation(n * m)[:p], (n, m))] = 1
print(array)


[[1 0 1 0 1]
 [0 0 0 1 0]
 [0 0 0 0 0]
 [1 0 0 0 0]
 [0 0 0 0 0]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [ ]:
import numpy as np
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

row_means = np.mean(matrix, axis=1)
normalized_matrix = matrix - row_means[:, np.newaxis]
print(normalized_matrix)


[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


#### 59. How to sort an array by the nth column? (★★☆)

In [ ]:
import numpy as np
array=np.array([[1,2,3],
                [4,5,6],
                [6,7,8]])
n=1
sorted=np.argsort(array[:,n])
sorted_array=array[sorted]
print(sorted_array)

[[1 2 3]
 [4 5 6]
 [6 7 8]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [ ]:
import numpy as np
array=np.array([[1,2,np.nan],
               [3,np.nan,np.nan],
                [5,6,np.nan]])
null_col=np.all(np.isnan(array),axis=0)
print(null_col)

[False False  True]


#### 61. Find the nearest value from a given value in an array (★★☆)

In [ ]:
import numpy as np
arr=np.array([1,2,10,15,6,20])
value=12
nearest=arr[np.abs(arr-value).argmin()]
print(nearest)

10


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [ ]:
import numpy as np
arr1=np.random.rand(1,3)
arr2=np.random.rand(3,1)
sum=np.sum(arr1+arr2)
print(sum)

10.743278568788863


#### 63. Create an array class that has a name attribute (★★☆)

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
name='array'
print(arr)
print(name)

[1 2 3 4 5]
array


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [ ]:
import numpy as np
v=np.array([1,2,3,4])
indices=np.array([1,3])
v[indices]+=1
print(v)

[1 3 3 5]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [ ]:
import numpy as np
X = np.array([10, 20, 30, 40, 50])
I = np.array([0, 1, 0, 2, 2])
F = np.zeros(max(I) + 1, dtype=int)
np.add.at(F, I, X)
print(F)

[40 20 90]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [ ]:
import numpy as np
image = np.random.randint(0, 256, (100, 100, 3), dtype=np.uint8)
colors = np.unique(image.reshape(-1, 3), axis=0).shape[0]
print(colors)

9997


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [ ]:
import numpy as np
arr=np.random.rand(3,4,5,6)
result=np.sum(arr,(-2,-1))
print(result)

[[13.50325013 15.52380171 14.48132751 15.85529629]
 [15.93828488 13.84462577 17.90577499 13.75427586]
 [13.84296346 13.76496672 15.46681453 15.90492513]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [ ]:
import numpy as np

D = np.array([10, 20, 30, 40, 50, 60])
S = np.array([1, 1, 2, 2, 3, 3])

means = [D[S == i].mean() for i in np.unique(S)]

print(means)


[15.0, 35.0, 55.0]


#### 69. How to get the diagonal of a dot product? (★★★)

In [ ]:
import numpy as np
a=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
b=np.array([[5,6,7],
            [8,9,1],
            [0,6,1]])
diagonal = np.sum(a * b.T, axis=1)
print(diagonal)

[ 21 105  66]




```
# This is formatted as code
```

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [ ]:
import numpy as np
vector=np.array([1,2,3,4,5])
new_vector=np.zeros(len(vector)*4-3)
new_vector[::4]=vector
print(new_vector)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [ ]:
import numpy as np
arr1=np.random.rand(5,5,3)
arr2=np.random.rand(5,5)
arr=arr2[:,:,np.newaxis]
result=arr1*arr
print(result)

[[[0.28132417 0.24105444 0.38076683]
  [0.56963954 0.62807296 0.16065001]
  [0.16321915 0.1674302  0.10930411]
  [0.08746879 0.01132738 0.12850291]
  [0.13012345 0.13921948 0.49042692]]

 [[0.20489327 0.141143   0.18198515]
  [0.24675941 0.34018136 0.38975376]
  [0.06057192 0.5350792  0.51775691]
  [0.22089127 0.17897766 0.34602832]
  [0.8771525  0.73773319 0.09758542]]

 [[0.05614954 0.51879996 0.15159563]
  [0.47246902 0.3897335  0.00897922]
  [0.38275147 0.22977943 0.11834297]
  [0.14027499 0.03250557 0.03255212]
  [0.0581458  0.2001993  0.25132118]]

 [[0.59557633 0.21406429 0.06372189]
  [0.16902691 0.31045467 0.09129429]
  [0.83589846 0.03642766 0.35605027]
  [0.03682056 0.05224535 0.06249926]
  [0.19190912 0.35306887 0.43035205]]

 [[0.09474824 0.10687638 0.12890204]
  [0.02000044 0.0377439  0.0556334 ]
  [0.18485423 0.26626311 0.48714931]
  [0.02052281 0.02579833 0.03105373]
  [0.44187374 0.04605547 0.48532391]]]


#### 72. How to swap two rows of an array? (★★★)

In [ ]:
import numpy as np
array=np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print(array)
print('='*10)
row1=0
row2=2
array[[row1,row2]]=array[[row2,row1]]
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[7 8 9]
 [4 5 6]
 [1 2 3]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [ ]:

triangles = [
    (0, 1, 2),
    (0, 2, 3),
    (0, 3, 4),
    (1, 2, 4),
    (2, 3, 4),
    (1, 4, 5),
    (3, 4, 5),
    (2, 5, 6),
    (4, 5, 6),
    (5, 6, 7)
]

segments = set()
for t in triangles:
    a, b, c = t
    segments.add(tuple(sorted((a, b))))
    segments.add(tuple(sorted((b, c))))
    segments.add(tuple(sorted((c, a))))

print(sorted(segments))


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [ ]:
import numpy as np
c=np.array([1,2,3,4,5])
a=np.repeat(np.arange(len(c)),c)
print(a)
print(np.bincount(a))


[0 1 1 2 2 2 3 3 3 3 4 4 4 4 4]
[1 2 3 4 5]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [ ]:
import numpy as np
def sliding_window_average(arr, window_size):
    window = np.ones(window_size) / window_size
    return np.convolve(arr, window, mode='valid')
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
window_size = 3
averages = sliding_window_average(arr, window_size)
print("Sliding window averages:", averages)

Sliding window averages: [2. 3. 4. 5. 6. 7. 8. 9.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [ ]:
import numpy as np
Z = np.array([1, 2, 3, 4, 5, 6])
result = np.vstack((Z[:-2], Z[1:-1], Z[2:])).T
print(result)


[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [ ]:
import numpy as np
bool_arr=np.array([True,False,False,True])
negate=np.logical_not(bool_arr)
print(negate)

[False  True  True False]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [ ]:
import numpy as np
P0 = np.array([(1, 2), (2, 3), (3, 4)])
P1 = np.array([(4, 5), (5, 6), (6, 7)])
p = np.array([3, 3])
def distance_point_to_line(P0, P1, p):
    distances = []
    for (x1, y1), (x2, y2) in zip(P0, P1):
        px, py = p
        numerator = abs((x2 - x1) * (y1 - py) - (x1 - px) * (y2 - y1))
        denominator = np.sqrt((x2 - x1)**2 + (y2 - y1)**2)
        distance = numerator / denominator
        distances.append(distance)
    return distances
distances = distance_point_to_line(P0, P1, p)
print(distances)


[0.7071067811865476, 0.7071067811865476, 0.7071067811865476]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [ ]:
import numpy as np
z=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
window=4
num=len(z)-window+1



#### 82. Compute a matrix rank (★★★)

In [ ]:
import numpy as np
array=np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
rank=np.linalg.matrix_rank(array)
print(rank)

2


#### 83. How to find the most frequent value in an array?

In [ ]:
import numpy as np
array=np.array([1,1,1,2,2,3,3,5,5,5,5,6,7,7,8,1])
counts=np.bincount(array)
frequency_value=np.argmax(counts)
print(frequency_value)

1


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [ ]:
import numpy as np
matrix=np.random.randint(0,10,(10,10))
block_size=3


[[4 9 6 7 7 3 0 7 1 4]
 [7 7 4 6 4 8 2 5 1 6]
 [6 2 2 6 6 5 3 8 3 1]
 [7 9 2 0 1 8 8 7 0 1]
 [7 9 7 8 0 9 4 8 0 9]
 [0 7 8 5 7 7 8 4 7 4]
 [3 6 2 5 8 4 1 3 9 6]
 [1 9 0 4 7 8 3 7 1 0]
 [5 6 7 4 3 0 9 0 7 3]
 [5 9 4 6 7 1 3 6 2 9]]


#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [ ]:
import numpy as np
data=np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
def make_matrix(matrix):
  return(matrix+matrix.T)/2
symetric_array=make_matrix(data)
print(symetric_array)

[[1. 3. 5.]
 [3. 5. 7.]
 [5. 7. 9.]]


#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [ ]:
import numpy as np

def sum_matrix_vector_products(matrices, vectors):
    result = np.zeros((vectors[0].shape[0], 1))
    for i in range(len(matrices)):
        result += np.dot(matrices[i], vectors[i])
    return result
p = 3
n = 4
matrices = [np.random.rand(n, n) for _ in range(p)]
vectors = [np.random.rand(n, 1) for _ in range(p)]
result = sum_matrix_vector_products(matrices, vectors)
print(result)


[[3.23829815]
 [3.45575215]
 [1.63124062]
 [2.63928744]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [ ]:
import numpy as np
arr = np.random.randint(1, 10, (16, 16))
block_sum = arr.reshape(4, 4, 4, 4).sum(axis=(2, 3))
print(block_sum)

[[90 85 91 75]
 [71 72 84 73]
 [75 82 98 84]
 [94 91 65 80]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

In [ ]:
import numpy as np
array=np.array([10,20,30,40,50,60,15])
max_value=np.max(array)
print(max_value)

60


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

In [ ]:
import numpy as np
struched_array=np.array([(1,'ahmed',22),(2,'said',20),(3,'saif',30)])
record_array=np.rec.array(struched_array)
print(record_array)

[['1' 'ahmed' '22']
 ['2' 'said' '20']
 ['3' 'saif' '30']]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [ ]:
import numpy as np
z=np.array([1,2,3,4,5])
copy=np.power(z,3)
print(copy)

[  1   8  27  64 125]


In [ ]:
import numpy as np
z=np.array([1,2,3,4,5])
copy=z*z*z
print(copy)

[  1   8  27  64 125]


In [ ]:
import numpy as np
z=np.array([1,2,3,4,5])
copy=np.prod([z,z,z],axis=0)
print(copy)

[  1   8  27  64 125]


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [ ]:
import numpy as np
matrix = np.array([
    [1, 2, 3],
    [4, 4, 6],
    [7, 8, 9],
    [1, 2, 2],
    [5, 6, 7],
    [8, 9, 8],
    [9, 10, 11],
    [12, 13, 14],
    [15, 15, 16],
    [17, 18, 19]
])

def extract_unique_rows_simple(mat):
    unique_rows = []
    for row in mat:
        if len(row) == len(set(row)):
            unique_rows.append(row)
    return np.array(unique_rows)
result = extract_unique_rows_simple(matrix)
print(result)


[[ 1  2  3]
 [ 7  8  9]
 [ 5  6  7]
 [ 9 10 11]
 [12 13 14]
 [17 18 19]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [ ]:
import numpy as np
vector=np.array([5,9,15],dtype=np.uint8)
binary_matrix = np.unpackbits(vector[:, np.newaxis], axis=1)
print(binary_matrix)

[[0 0 0 0 0 1 0 1]
 [0 0 0 0 1 0 0 1]
 [0 0 0 0 1 1 1 1]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [ ]:
import numpy as np
array=np.array([[1,2,3],
                [4,5,6],
                [1,2,3],
                [7,8,9],
                [7,8,9]])
unique=np.unique(array,axis=0)
print(unique)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [ ]:
import numpy as np
arr1=np.array([1,2,3,4])
arr2=np.array([4,5,6,7])
inner=np.dot(arr1,arr2)
print(inner)

60


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [ ]:
import numpy as np
X = np.array([0, 1, 2, 4, 7])
Y = np.array([0, 1, 1, 2, 3])

distances = np.sqrt(np.diff(X)**2 + np.diff(Y)**2)
cumulative_distances = np.insert(np.cumsum(distances), 0, 0)

num_samples = 10
equidistant_points = np.linspace(0, cumulative_distances[-1], num_samples)

X_samples = np.interp(equidistant_points, cumulative_distances, X)
Y_samples = np.interp(equidistant_points, cumulative_distances, Y)
print("X samples:", X_samples)
print("Y samples:", Y_samples)


X samples: [0.         0.61381262 1.3219107  2.16991687 2.94633525 3.72275362
 4.52945186 5.3529679  6.17648395 7.        ]
Y samples: [0.         0.61381262 1.         1.08495844 1.47316762 1.86137681
 2.17648395 2.4509893  2.72549465 3.        ]


#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [ ]:
import numpy as np

def select_multinomial_rows(X, n):
    # تحقق من أن جميع العناصر في الصف هي أعداد صحيحة
    is_integer = np.all(np.mod(X, 1) == 0, axis=1)

    # تحقق من أن مجموع الصف يساوي n
    sum_equals_n = np.sum(X, axis=1) == n

    valid_rows = is_integer & sum_equals_n

    return X[valid_rows]

X = np.array([[2, 3, 5],
              [1, 4, 5],
              [0, 2, 8],
              [3, 3, 4]])

n = 10

result = select_multinomial_rows(X, n)
print(result)


[[2 3 5]
 [1 4 5]
 [0 2 8]
 [3 3 4]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)